"""Deterministic projections from canonical MCP manifests."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

from .manifest_loader import ManifestCatalog
from .manifest_models import CompanionRuntime, MCPManifest, ToolContract
from .manifest_validator import resolve_runtime_url

GENERATED_HEADER = (
    "Generated by scripts/generate_mcp_artifacts.py; do not edit manually."
)


def _json(payload: Any) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def _yaml(payload: Any) -> str:
    return f"# {GENERATED_HEADER}\n" + yaml.safe_dump(
        payload, sort_keys=False, allow_unicode=True, default_flow_style=False
    )


def _contract_payload(contract: ToolContract) -> dict[str, Any]:
    return {
        "status": contract.status,
        "required_scope": contract.required_scope,
        "mutating": contract.mutating,
        "risk": contract.risk.model_dump(mode="json"),
        "secret_reference_only": contract.secret_reference_only,
        "input_schema": contract.input_schema,
        "output_schema": contract.output_schema,
    }


def render_mcp_json(catalog: ManifestCatalog) -> str:
    servers: dict[str, Any] = {}
    for manifest in catalog.executable():
        if not (manifest.transport.stdio and manifest.runtime.mode == "local"):
            continue
        servers[manifest.id] = {
            "command": manifest.runtime.command,
            "args": manifest.runtime.args,
            "cwd": f"./{manifest.runtime.cwd}",
        }
    return _json(
        {
            "_comment": GENERATED_HEADER,
            "mcpServers": servers,
        }
    )


def render_runtime_registry(catalog: ManifestCatalog) -> str:
    services: dict[str, Any] = {}
    for manifest in catalog.executable():
        if not (manifest.registry.enabled or manifest.gateway.enabled):
            continue
        entry: dict[str, Any] = {
            "status": manifest.status,
            "classification": manifest.classification.model_dump(mode="json"),
            "owner": manifest.ownership.model_dump(mode="json"),
            "transport": manifest.transport.model_dump(mode="json"),
            "security": manifest.security.model_dump(mode="json"),
            "gateway_enabled": manifest.gateway.enabled,
            "registry_enabled": manifest.registry.enabled,
        }
        if manifest.runtime.mode == "local":
            entry["url"] = resolve_runtime_url(manifest)
            if manifest.runtime.base_url_env:
                entry["url_env"] = manifest.runtime.base_url_env
        elif manifest.runtime.mode == "external":
            entry["url_env"] = manifest.runtime.base_url_env
        policies = {
            name: _contract_payload(contract)
            for (provider_id, name), contract in sorted(catalog.contracts.items())
            if provider_id == manifest.id
        }
        if policies:
            entry["tool_policies"] = policies
        services[manifest.id] = entry
    return _json({"schema_version": 1, "generated": True, "services": services})


def _compose_service(manifest: MCPManifest) -> dict[str, Any]:
    runtime = manifest.runtime
    service: dict[str, Any] = {}
    if runtime.dockerfile:
        service["build"] = {
            "context": runtime.build_context or ".",
            "dockerfile": runtime.dockerfile,
        }
        if runtime.build_ssh:
            service["build"]["ssh"] = ["default"]
        if runtime.build_secrets:
            service["build"]["secrets"] = list(runtime.build_secrets)
    if manifest.network.host_port and manifest.network.internal_port:
        service["ports"] = [
            f"{manifest.network.host_port}:{manifest.network.internal_port}"
        ]
    environment = dict(runtime.environment)
    if manifest.network.internal_port:
        environment.setdefault("MCP_PORT", str(manifest.network.internal_port))
    if environment:
        service["environment"] = environment
    if runtime.volumes:
        service["volumes"] = runtime.volumes
    if runtime.depends_on:
        service["depends_on"] = runtime.depends_on
    if runtime.command:
        service["command"] = [runtime.command, *runtime.args]
    if manifest.network.internal_port:
        ready_path = manifest.transport.canonical_http.health_ready
        service["healthcheck"] = {
            "test": [
                "CMD",
                "python",
                "-c",
                f"import urllib.request; urllib.request.urlopen('http://127.0.0.1:{manifest.network.internal_port}{ready_path}', timeout=2)",
            ],
            "interval": "30s",
            "timeout": "3s",
            "retries": 3,
        }
    service["networks"] = ["mcp-network"]
    service["restart"] = "unless-stopped"
    service["labels"] = [
        "generated-by=platform-devs-control-plane",
        f"mcp={manifest.id}",
        f"status={manifest.status}",
    ]
    return service


def _compose_companion(
    manifest: MCPManifest, companion: CompanionRuntime
) -> dict[str, Any]:
    service: dict[str, Any] = {
        "command": companion.command,
        "environment": companion.environment,
        "networks": ["mcp-network"],
        "restart": "unless-stopped",
        "labels": [
            "generated-by=platform-devs-control-plane",
            f"companion-of={manifest.id}",
            f"status={manifest.status}",
        ],
    }
    if manifest.runtime.dockerfile:
        service["build"] = {
            "context": manifest.runtime.build_context or ".",
            "dockerfile": manifest.runtime.dockerfile,
        }
        if manifest.runtime.build_ssh:
            service["build"]["ssh"] = ["default"]
        if manifest.runtime.build_secrets:
            service["build"]["secrets"] = list(manifest.runtime.build_secrets)
    if companion.ports:
        service["ports"] = companion.ports
    if companion.depends_on:
        service["depends_on"] = companion.depends_on
    return service


def render_compose(catalog: ManifestCatalog) -> str:
    services: dict[str, Any] = {}
    for manifest in catalog.executable():
        if manifest.runtime.mode != "local":
            continue
        services[manifest.runtime.service_name or manifest.id] = _compose_service(
            manifest
        )
        for companion in manifest.companions:
            services[companion.service_name] = _compose_companion(manifest, companion)
    # Runtime dependencies are infrastructure, not MCP providers; they deliberately
    # remain a small fixed substrate rather than entries in the MCP product catalog.
    services["redis"] = {
        "image": "redis:7-alpine",
        "command": [
            "sh",
            "-c",
            'exec redis-server --requirepass "$${REDIS_PASSWORD}"',
        ],
        "environment": {"REDIS_PASSWORD": "${REDIS_PASSWORD:?required}"},
        "networks": ["mcp-network"],
        "restart": "unless-stopped",
    }
    services["postgres"] = {
        "image": "postgres:16-alpine",
        "environment": {
            "POSTGRES_USER": "${POSTGRES_USER:?required}",
            "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD:?required}",
            "POSTGRES_DB": "${POSTGRES_DB:-platform_dev}",
        },
        "volumes": ["postgres-data:/var/lib/postgresql/data"],
        "networks": ["mcp-network"],
        "restart": "unless-stopped",
    }
    gateway = services.get("mcp-gateway")
    if gateway is not None:
        gateway_environment = gateway.setdefault("environment", {})
        for manifest in catalog.executable():
            env_name = manifest.runtime.base_url_env
            if not (manifest.gateway.enabled and env_name):
                continue
            if manifest.runtime.mode == "external":
                gateway_environment.setdefault(env_name, f"${{{env_name}:?required}}")
            else:
                gateway_environment.setdefault(env_name, f"${{{env_name}:-}}")
        gateway["volumes"] = [
            "./generated/mcp-runtime-registry.json:/app/mcp-runtime-registry.json:ro"
        ]
        gateway["depends_on"] = ["postgres", "redis"] + [
            m.runtime.service_name
            for m in catalog.executable()
            if m.gateway.enabled and m.runtime.mode == "local" and m.id != "mcp-gateway"
        ]
    registry = services.get("mcp-registry")
    if registry is not None:
        registry["volumes"] = [
            "./mcp-registry.py:/app/mcp-registry.py:ro",
            "./generated/mcp-runtime-registry.json:/app/mcp-runtime-registry.json:ro",
        ]
    named_volumes: dict[str, Any] = {"postgres-data": {}}
    for manifest in catalog.executable():
        if manifest.runtime.mode != "local":
            continue
        for volume in manifest.runtime.volumes:
            source = volume.split(":", 1)[0]
            if (
                source
                and "/" not in source
                and "\\" not in source
                and not source.startswith(".")
            ):
                named_volumes[source] = {}
    build_secret_ids = sorted(
        {
            secret
            for manifest in catalog.executable()
            if manifest.runtime.mode == "local"
            for secret in manifest.runtime.build_secrets
        }
    )
    payload: dict[str, Any] = {
        "name": "platform-devs-control-plane",
        "services": services,
        "networks": {"mcp-network": {"driver": "bridge"}},
        "volumes": named_volumes,
    }
    if build_secret_ids:
        payload["secrets"] = {
            secret: {"file": f"${{{secret.upper()}_FILE:?required}}"}
            for secret in build_secret_ids
        }
    return _yaml(payload)


def render_catalog_doc(catalog: ManifestCatalog) -> str:
    rows = []
    for manifest in sorted(catalog.manifests.values(), key=lambda item: item.id):
        runtime = manifest.runtime.mode
        owner = manifest.ownership.source_repo
        rows.append(
            f"| `{manifest.id}` | {manifest.status} | {manifest.classification.type} | "
            f"{runtime} | `{owner}` | {'yes' if manifest.gateway.enabled else 'no'} |"
        )
    return "\n".join(
        [
            "# MCP catalog",
            "",
            f"> {GENERATED_HEADER}",
            "",
            "Only `active` entries are projected into runtime artifacts. `planned` entries are product catalog only.",
            "",
            "| MCP | Status | Type | Runtime | Source repository | Gateway |",
            "|---|---|---|---|---|---|",
            *rows,
            "",
        ]
    )


def render_schemas() -> dict[Path, str]:
    return {
        Path("schemas/mcp-manifest.schema.json"): _json(
            MCPManifest.model_json_schema()
        ),
        Path("schemas/tool-contract.schema.json"): _json(
            ToolContract.model_json_schema()
        ),
    }


def render_all(catalog: ManifestCatalog) -> dict[Path, str]:
    outputs = {
        Path(".mcp.json"): render_mcp_json(catalog),
        Path("generated/mcp-runtime-registry.json"): render_runtime_registry(catalog),
        Path("docker-compose.yml"): render_compose(catalog),
        Path("docs/generated/mcp-catalog.md"): render_catalog_doc(catalog),
    }
    outputs.update(render_schemas())
    return outputs


def write_all(catalog: ManifestCatalog) -> list[Path]:
    changed: list[Path] = []
    for relative, content in render_all(catalog).items():
        path = catalog.root / relative
        previous = path.read_text(encoding="utf-8") if path.exists() else None
        if previous != content:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            changed.append(relative)
    return changed


def check_all(catalog: ManifestCatalog) -> list[str]:
    drift: list[str] = []
    for relative, expected in render_all(catalog).items():
        path = catalog.root / relative
        if not path.exists():
            drift.append(f"missing generated artifact: {relative}")
        elif path.read_text(encoding="utf-8") != expected:
            drift.append(f"generated artifact drift: {relative}")
    return drift
